services:
  backend:
    restart: always
    image: ghcr.io/dtcooper/raspvid-backend:latest
    stop_signal: SIGINT
    build:
      context: backend
    volumes:
      - "${VIDEOS_DIR:?VIDEOS_DIR needs to be set. See .env file.}:/videos"
      - ./.env:/.env:ro
    devices:
      - /dev/vchiq:/dev/vchiq
      - /dev/fb0:/dev/fb0
      - /dev/tty1:/dev/tty1  # For fbi
    cap_add:
      - SYS_TTY_CONFIG  # For fbi

  frontend:
    container_name: frontend
    restart: "no"
    image: node:18
    volumes:
      - ./.env:/.env
      - ./frontend:/app
    profiles:
      - frontend

  nginx:
    restart: always
    image: jonasal/nginx-certbot:3.2.0-nginx1.23.0-alpine
    depends_on:
      - backend
      - logs
    volumes:
      - ./backend/nginx.conf:/etc/nginx/templates/backend.conf.template:ro
      - nginx_secrets:/etc/letsencrypt
    ports:
      - 80:80
      - 443:443
    environment:
      - "DOMAIN_NAME=${DOMAIN_NAME:?DOMAIN_NAME needs to be set. See .env file.}"
      - "CERTBOT_EMAIL=${CERTBOT_EMAIL:?CERTBOT_EMAIL needs to be set. See .env file.}"

volumes:
  nginx_secrets:
