services:
  player:
    image: pitv-player
    build:
      context: player
      args:
      - "DEBUG=${DEBUG:-0}"
    volumes:
      - "./player:/app"
    # devices:
    #   - /dev/vchiq:/dev/vchiq
    #   - /dev/snd:/dev/snd
