services:
  backend:
    restart: always
    image: ghcr.io/dtcooper/pitv-backend:latest
    stop_signal: SIGINT
    depends_on:
      - lirc
    build:
      context: backend
    volumes:
      - "${VIDEOS_DIR:?VIDEOS_DIR needs to be set. See .env file.}:/videos"
      - ./.env:/.env:ro
    devices:
      - /dev/vchiq:/dev/vchiq
      - /dev/snd:/dev/snd

  overlay:
    restart: always
    image: ghcr.io/dtcooper/pitv-overlay:latest
    depends_on:
      - backend
    build:
      context: overlay
    volumes:
      - ./.env:/.env:ro
    devices:
      - /dev/vchiq:/dev/vchiq
      - /dev/fb0:/dev/fb0

  lirc:
    restart: always
    image: ghcr.io/dtcooper/pitv-lirc:latest
    build:
      context: lirc
    devices:
      - /dev/bus/usb:/dev/bus/usb

  nginx:
    restart: always
    image: jonasal/nginx-certbot:3.2.0-nginx1.23.0-alpine
    depends_on:
      - backend
    volumes:
      - ./nginx.conf:/etc/nginx/templates/backend.conf.template:ro
      - nginx_secrets:/etc/letsencrypt
    ports:
      - 80:80
      - 443:443
    environment:
      - "DOMAIN_NAME=${DOMAIN_NAME:?DOMAIN_NAME needs to be set. See .env file.}"
      - "CERTBOT_EMAIL=${CERTBOT_EMAIL:?CERTBOT_EMAIL needs to be set. See .env file.}"

  frontend:
    container_name: frontend
    restart: "no"
    image: node:18
    working_dir: /app
    command: sh -c 'if [ ! -d node_modules/ ] ; then npm install ; fi && npm run dev'
    volumes:
      - ./.env:/.env
      - ./frontend:/app
    profiles:
      - frontend
    ports:
      - 8080:8080

volumes:
  nginx_secrets:
