services:
  api:
    restart: always
    image: ghcr.io/dtcooper/raspvid-api:latest
    build:
      context: api
    volumes:
      - "${VIDEOS_DIR:?VIDEOS_DIR needs to be set. See .env file.}:/videos"
      - ./.env:/.env:ro
    devices:
      - /dev/vchiq:/dev/vchiq
      - /dev/fb0:/dev/fb0
      - /dev/tty1:/dev/tty1  # For fbi
    cap_add:
      - SYS_TTY_CONFIG  # For fbi
    environment:
      - "DEBUG=${DEBUG:-0}"

  nginx:
    restart: always
    image: jonasal/nginx-certbot:3.1.2-nginx1.21.6-alpine
    depends_on:
      - api
    volumes:
      - ./api/nginx.conf:/etc/nginx/templates/api.conf.template:ro
      - nginx_secrets:/etc/letsencrypt
    ports:
      - 80:80
      - 443:443
    environment:
      - "DOMAIN_NAME=${DOMAIN_NAME:?DOMAIN_NAME needs to be set. See .env file.}"
      - "CERTBOT_EMAIL=${CERTBOT_EMAIL:?CERTBOT_EMAIL needs to be set. See .env file.}"

volumes:
  nginx_secrets:
