[tool.poetry]
name = "pitv"
version = "0.1.0"
description = "Raspberry Pi TV"
authors = ["David Cooper <david@dtcooper.com>"]
license = "MIT"

[tool.poetry.dependencies]
python = "^3.12"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
