name: Build and push
description: Build and push jewpizza docker containers

inputs:
  container:
    description: Container name
    required: true
  token:
    description: GitHub token
    required: true

runs:
  using: composite
  steps:
    -
      name: Set variables
      id: vars
      shell: bash
      run: |
        USERNAME="$(echo "$GITHUB_REPOSITORY_OWNER" | tr '[:upper:]' '[:lower:]')"
        echo "::set-output name=cache-tag::ghcr.io/${USERNAME}/raspvid-cache:${{ inputs.container }}"
        echo "::set-output name=repo::ghcr.io/${USERNAME}/raspvid-${{ inputs.container }}"
        echo "::set-output name=sha::$(echo ${GITHUB_SHA} | cut -c 1-8)"
        echo "::set-output name=username::${USERNAME}"
    -
      name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2
    -
      name: Set up QEMU
      uses: docker/setup-qemu-action@v2
      if: inputs.dev == '1'
    -
      name: Login to Github Container Registry
      uses: docker/login-action@v2
      with:
        registry: ghcr.io
        username: ${{ steps.vars.outputs.username }}
        password: ${{ inputs.token }}
    -
      name: Build and push
      uses: docker/build-push-action@v3
      with:
        push: true
        platforms: linux/arm64
        context: ./${{ inputs.container }}/
        file: ./${{ inputs.container }}/Dockerfile
        tags: |
          ${{ steps.vars.outputs.repo }}:latest
          ${{ steps.vars.outputs.repo }}:${{ steps.vars.outputs.sha }}
        cache-from: type=registry,ref=${{ steps.vars.outputs.cache-tag }}
        cache-to: type=registry,ref=${{ steps.vars.outputs.cache-tag }},mode=max
