name: Frontend deploy

on:
  push:
    branches:
      - main

concurrency:
  group: frontend-deploy
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-20.04
    name: Build container
    steps:
      -
        name: Checkout
        uses: actions/checkout@v3
      -
        name: Setup node
        uses: actions/setup-node@v3
        with:
          node-version: 16
      -
        name: Create envfile
        uses: SpicyPizza/create-envfile@v1.3
        with:
          envkey_DOMAIN_NAME: ${{ secrets.DEPLOY_DOMAIN_NAME }}
          envkey_TITLE: ${{ secrets.DEPLOY_TITLE }}
      -
        name: Build site
        run: |
          cd frontend
          npm install
          npm run build
          cd dist
      -
        name: Clear current build
        uses: appleboy/ssh-action@master
        env:
          DIRECTORY: ${{ secrets.DEPLOY_DIRECTORY }}
        with:
          host: ${{ secrets.SSH_HOST }}
          port: ${{ secrets.SSH_PORT }}
          username: ${{ secrets.SSH_USERNAME }}
          key: ${{ secrets.SSH_KEY }}
          fingerprint: ${{ secrets.SSH_FINGERPRINT }}
          envs: DIRECTORY
          script: |
            cd "$DIRECTORY"
            rm -vrf {*,.*}
      -
        name: Upload new build
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.SSH_HOST }}
          port: ${{ secrets.SSH_PORT }}
          username: ${{ secrets.SSH_USERNAME }}
          key: ${{ secrets.SSH_KEY }}
          fingerprint: ${{ secrets.SSH_FINGERPRINT }}
          source: "*"
          target: ${{ secrets.DEPLOY_DIRECTORY }}
