name: Frontend deploy

on:
  push:
    branches:
      - main

concurrency:
  group: frontend-deploy
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-20.04
    name: Build container
    steps:
      -
        name: Checkout
        uses: actions/checkout@v3
      -
        name: Setup node
        uses: actions/setup-node@v3
        with:
          node-version: 16
      -
        name: Create envfile
        uses: SpicyPizza/create-envfile@v1.3
        with:
          envkey_DOMAIN_NAME: ${{ secrets.DEPLOY_DOMAIN_NAME }}
          envkey_TITLE: ${{ secrets.DEPLOY_TITLE }}
      -
        name: Build site
        run: |
          cd frontend
          npm install
          npm run build
      -
        name: Setup tmate session
        uses: mxschmitt/action-tmate@v3
